use_frameworks!

platform :ios, '8.0'

target 'GXDLearning_Example' do
  pod 'GXDLearning', :path => '../'

  target 'GXDLearning_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
